### ISSUE TITLE
Editing and Finalize Website openinfra.id

### ISSUE THREAD

**Issue by aryulianto** [openinfraid/general#2]
Domain: https://dev.openinfra.id
Repo: https://gitlab.com/openstackindo/web-openinfraid

**Comment by AjiArya** [comment]
Working on it, issue(s) will be created in https://gitlab.com/openstackindo/web-openinfraid to make tracking and review.

Kanban Board: https://gitlab.com/openstackindo/web-openinfraid/-/boards

**Comment by aryulianto** [comment]
will close this issue and create specific issues
