### ISSUE TITLE
Design Poster Publikasi Call For Speaker - Regular Meetup

### ISSUE THREAD

**Issue by aryulianto** [openinfraid/general#20]
- memuat panggilan untuk pembicara/call for speaker - regular meetup
- memuat link guideline: s.id/ooid-guideline
- memuat link pendaftaran:  s.id/ooid-speaker
- memuat kata-kata "SHARE YOUR IDEAS, KNOWLEDGE, AND EXPERIENCES
BECOME A SPEAKER!"
- ukuran poster: TBD
(@bajinra biasanya berapa ya?)

**Comment by itsmefdil** [comment]
Aku assign ini ya mas @aryulianto @bajinra

**Comment by itsmefdil** [comment]
@aryulianto  deadlinenya kapan ya ?

**Comment by aryulianto** [comment]
sudah ditambahkan ya mas @friczky due datenya di https://github.com/orgs/openinfraid/projects/3?pane=issue&itemId=17999467

**Comment by itsmefdil** [comment]
Ok mas @aryulianto

**Comment by aryulianto** [comment]
makasih banyak mas @friczky
