### ISSUE TITLE
Create Poster for Meetup Januari - Bogor

### ISSUE THREAD

**Issue by aryulianto** [openinfraid/general#22]
ukuran: 1080 x 1528 & 1200 x 675

pembicara dan judul:
https://docs.google.com/spreadsheets/d/1opFwSJy-oe-gn0CWn59Gr8qhv0cjqOHl7dy_g1MIzdg/edit#gid=1363661902

tempat: SMKN 1 Cibinong - Ruangan XXX

**Comment by whippedcreamm** [comment]
ukuran: 1080 x 1528 & 1200 x 675

pembicara dan judul:
https://docs.google.com/spreadsheets/d/1opFwSJy-oe-gn0CWn59Gr8qhv0cjqOHl7dy_g1MIzdg/edit#gid=1363661902

tempat: SMKN 1 Cibinong - Ruangan Lab SIJA 2

logo yang perlu dicantumkan: SMK Negeri 1 Cibinong & Nevtik
- [Logo Nevtik](https://images.app.goo.gl/WhuE4ReiepL6dosp7)
- [Logo SMKN 1 Cibinong](https://www.google.co.id/imgres?imgurl=https%3A%2F%2Fsmkn1cibinong.sch.id%2Fmain%2Fwp-content%2Fuploads%2F2019%2F03%2Fcropped-SMKLOG-12.png&imgrefurl=https%3A%2F%2Fsmkn1cibinong.sch.id%2Fmain%2Fkurikulum%2Fkompetensi-keahlian%2F&tbnid=sUY7L91e7ji4DM&vet=1&docid=4wqj1eKcs3MQMM&w=121&h=121&hl=en-GB&source=sh%2Fx%2Fim)
